version: '3'
services:
  zomatomart:
    container_name: zomatomart
    duild: ./zomatomart
    ports:
        - '1111:80'
    volumes: 
        - zomato_volume: /usr/share/nginx/html
    deploy: 
      replicas: 6
    networks:
      - app-network
volumes: 
    zomato_volume:
networks:
  app-network:
    driver: overlay
    
        
