version: '3'
services:
  zomatomart:
    container_name: zomatomart
    duild: ./zomatomart
    ports:
        - '1111:80'
    deploy: 
      replicas: 6
    networks:
      - app-network
networks:
  app-network:
    driver: overlay
    
        
