version: '3.9'
services:
  zomatomart:
    container_name: myzomato
    image: sivakrishna630/siva-repo1:siva-zomato1
    ports:
        - '1111:80'
    deploy: 
      replicas: 6
    networks:
      - app-network
networks:
  app-network:
    driver: overlay
    
        
